estados_venezuela = {
    "Amazonas": ["puerto ayacucho", "guayana"],
    "Anzoátegui": ["el trigre", "anaco", "barcelona", "el tigrito", "lecheria", "puerto la cruz", "aragua de barcelona"],
    "Apure": ["san fernando de apure", "san fernando", "araure"],
    "Aragua": ["maracay", "palo negro", "turmero", "maeacay", "la victoria", "cagua", "la morita1", "aragua", "la victoria edo aragua", "maracay.", "el consejo estado aragua", "santa rita maracay", "turmero, estado aragua", "la victoria aragua", "maracay- turmero", "palo negrro", "santa rita aragua", "yagua", "palo negro, aragua", "el limón", "maracay edo aragua", "msracay", "msracay", "palo negro - aragua", "maracay aragua", "caguas"],
    "Barinas": ["barinas"],
    "Bolívar": ["puerto ordaz", "ciudad bolivar", "ciudad guayana", "ciudad bolívar"],
    "Carabobo": ["moron", "valencia", "guacara", "montalban", "puerto cabello", "carabobo", "naguanagua", "puerto cabello carabobo", "carrizal", "san diego", "los guayos", "valencia edo. carabobo", "valencia, naguanagua", "valencia. venezuela", "valencia. venezuela", "san joaquin", "san diego de los altos", "valencia estado carabobo", "valencia, los guayos", "valencia, edo. carabobo", "san joaquin, estado carabobo", "ciudad alianza", "naguanagua. estado carabobo", "puerto cabell", "san joaquin*", "san joaquin", "valencia, carabobo", "nagauanagua", "ciudad zamora mzna. 4-f", "san digo", "san diego carabobo", "nagua", "urb. el bosque. valencia edo. carabobo", "guacara edo carabobo", "puerto cabello", "valenciq","valencia,  naguanagua","valencia , los guayos","san joaquín","guacaipuro","puerto  cabello"],
    "Cojedes": ["san carlos", "tinaco", "tinaquillo"],
    "Delta Amacuro": ["tucupita"],
    "Desconocidos": ["NaN","desconocido", "primero de mayo", "venezuela", "urb. los cocos sur", "la vaquera", "cjto. res. ops torre 3", "468", "el consejo", "palavecino", "allen", "san rafael de carvajal,/ carvajal", "11201663", "mario briceño iragorry", "cordero lomas blanca", "la concepcion", "13912257", "barcel", "el concejo", "libertad", "30", "275", "hhhhhh", "plc", "la concepción", "parroquia santa teresa", "peribeca", "san rafael del mojan", "4", "ciudad", "ed. mar azul t-b"],
    "Falcón": ["punto fijo", "churuguara", "coro", "chichiriviche", "la vela de coro", "santa ana de coro"],
    "Guárico": ["san juan de los morros", "altagracia de orituco"],
    "Lara": ["carora", "cabudare", "barquisimeto", "barquisimeto gxtest2al", "barquisimeto gxtes2al", "cabudare estado lara", "iribarren", "cabude", "barquisimeto*", "bqto"],
    "Mérida": ["merida", "mérida", "el vigia", "ejido, mérida", "mérida, venezuela"],
    "Miranda": ["guanares", "charallave", "los teques", "guatire", "miranda", "san antonio de los altos", "carrizal, estado miranda", "guarenas, miranda", "cuarenas", "guarenas, edo. miranda", "ciudad casarapa", "ocumare del tuy", "mariche", "guatires", "san antonio", "san josé d/los altos", "gurenas", "san josé de los altos", "los teqes", "guatire, edo miranda, venezuela", "*los teques", "guatire, edo. miranda. venezuela", "altos mirandinos", "higuerote"],
    "Monagas": ["maturin", "maturín"],
    "Nueva Esparta": ["margarita", "porlamar", "pampatar", "catia la mar"],
    "Portuguesa": ["guanare", "acarigua"],
    "Sucre": ["cumana", "cumanacoa", "municipio sucre", "carupano", "cumaná", "sucre"],
    "Táchira": ["san cristobal", "san cristóbal", "tachira", "capacho", "tariba", "los rastrojos", "cordero", "táriba", "caneyes", "táchira", "tucape", "san rafael cárdenas tachira venezuela", "san cristobal edo tachira", "capacho viejo", "san cristobal de tac"],
    "Trujillo": ["valera"],
    "Vargas (La Guaira)": ["la guaira", "vargas", "maiquetía, estado la guaira"],
    "Yaracuy": ["san felipe", "chivacoa", "yaritagua"],
    "Zulia": ["cabimas", "maracaibo", "zulia", "ciudad ojeda", "santa rita", "ciudad ojeda.", "ojeda", "maraxaibo", "maracaibo*"],
    "Distrito Capital (Caracas)": ["caracas", "caracass", "el hatillo", "csracas", "la tahona", "edif virrey, calle caurimare , caracas", "gran caracas", "caracas venezuela", "caricuao", "baruta", "libertador", "caracas gxtest2al", "distrito capital", "caracs", "caracas (miranda)", "maracas", "el hatillo-la unión", "baracas", "chacao", "la candelaria", "carcas", "municipio el hatillo", "caracas-baruta", "ccs", "la candelaria mbi", "el hatillo la unión corralito", "caraacs", "lagunillas", "caracas09966564", "caracas,", "caracas, el hatillo", "lagunillas", "urb. libertadores", "cara as", "caracas (d.c.)"],
    "Internacionales": ["santiago", "la paz", "palmira", "ejido", "bogota", "sn francisco", "chile", "zamora", "miami", "san francisco", "girardot", "san. francisco"]
}